my_db/urls.py
from django.contrib import admin
from django.urls import path
from my_app import views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.base, name ='index'),
    path('login/',views.login,name = 'login'),
    path('signup/',views.signup, name= 'signup'),
    path('instructor/',views.instructor, name= 'instructor'),
    path('inst_signup/',views.instsignup, name= 'inst_signup'),
    path('inst_login/',views.instlogin, name= 'inst_login'),
    path('user_page/',views.userpage, name= 'userpage'),
    path('mycourse/<int:pk>/',views.mycourse, name= 'mycourse'),
    path('inst_page/',views.instpage, name= 'instpage'),
    path('signout/',views.signout, name='signout'),
    path('addcourse/',views.addcourse, name='addcourse'),
    path('corusel/',views.corusel, name='corusel'),
    path('navbar/',views.navbar, name='navbar'),
    path('pdfs/',views.pdfs, name='pdfs'),
    path('videos/',views.videos, name='videos'),
    path('quiz/',views.quiz, name='quiz'),
    path('main/<int:pk>/<int:usr>/', views.main_view, name="main-view"),
    path('rate/', views.rate_image, name='rate-view'),
    path('coursedetail/<int:pk>/<int:user>/',views.coursedetail,name='coursedetail'),
    path('courseview/<int:pk>/<int:user>/', views.courseview, name='courseview'),
    path('search/',views.search,name='search'),
    path('instructor_page/',views.instructorpage,name='instructorpage'),
    path('instructor2/',views.instructor2,name='instructor2'),
    path('delete/<int:pk>/<int:id>/' ,views.delete,name='delete')
   
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

my_app/models.py
from  embed_video.fields  import  EmbedVideoField
# Create your models here.
from django.db import models
from django.db.models import Avg
from django.core.validators import MaxValueValidator, MinValueValidator

class User(models.Model):
    fname = models.CharField(max_length = 20)
    lname = models.CharField(max_length = 20)
    email = models.EmailField(max_length =50)
    passwd = models.CharField(max_length = 16)
    sex = models.CharField(max_length =10)

    def __str__(self):
        return self.fname +' '+ self.lname

class Instructor(models.Model):
    fname = models.CharField(max_length = 20)
    lname = models.CharField(max_length = 20)
    email = models.EmailField(max_length =50)
    passwd = models.CharField(max_length = 16)
    sex = models.CharField(max_length =10)
    image = models.ImageField(null = True,blank = True,upload_to = 'images/')

    def __str__(self):
        return self.fname +' '+ self.lname

class Category(models.Model):
    category_id = models.BigAutoField(primary_key =True)
    name = models.CharField(max_length = 50)
   

    def __str__(self):
        return self.name
  



class Courses(models.Model):
    courses_id = models.BigAutoField(primary_key = True)
    name = models.CharField(max_length = 50)
    content = models.TextField(max_length = 50)
    category_id = models.ForeignKey(Category,on_delete = models.CASCADE)
    instructor = models.ForeignKey(Instructor,on_delete = models.CASCADE)
    user = models.ManyToManyField(User,related_name ="user",through="Courses_User")
    image = models.ImageField(upload_to = 'images/')
    intro_Video = EmbedVideoField()

   
    def __str__(self):
        return self.name

class Videos(models.Model):
    vid_name = models.CharField(max_length=50)
    vid = EmbedVideoField()
    course = models.ForeignKey(Courses,on_delete = models.CASCADE)
    
    def __str__(self):
        return self.vid_name
   

class Quiz(models.Model):
    quiz_name = models.CharField(max_length=50)
    quiz_url = models.URLField()
    course= models.ForeignKey(Courses,on_delete = models.CASCADE)
    

    def __str__(self):
        return self.quiz_name
   


class Pdfs(models.Model):
    pdf_name = models.CharField(max_length=50)
    file  = models.FileField(upload_to ='pdfs/')
    course = models.ForeignKey(Courses,on_delete = models.CASCADE)
   

    def __str__(self):
        return self.pdf_name


class Rating(models.Model):
    courses_id = models.ForeignKey(Courses,on_delete=models.CASCADE)
    score = models.IntegerField(default=0,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(0),
        ]
    )

    def __str__(self):
        return str(self.pk)



class Courses_User(models.Model):
    courses_id = models.ForeignKey(Courses,on_delete=models.CASCADE)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    enroll_date =  models.DateTimeField(auto_now_add=True) 

    class Meta:
        unique_together = ("user_id","courses_id")

templates/addcourse.html
{% extends 'inst_page.html' %}
{% block content %}
{% load static %}

  
    <link rel="stylesheet" href="{% static '/css/base.css' %}">

   <!-- <link rel="stylesheet" href="{% static '/css/dark_mode.css' %}">-->


    <link rel="stylesheet" href="{% static '/css/nav_sidebar.css' %}">
    <script src="{% static 'css/nav_sidebar.css' %}" defer=""></script>

    <link rel="stylesheet" href="{% static '/css/forms.css' %}">

    <link rel="stylesheet" href="{% static '/css/responsive.css' %}">

        

  

   


    <!-- Container -->
    <div id="container">

        <div class="main" id="main">

            <div class="content">

                <!-- Content -->
                <div id="content" class="colM">


                    <div id="content-main">

                        <form enctype="multipart/form-data" method="post" action="{% url 'addcourse' %}" id="courses_form" novalidate="">
                                {% csrf_token %}
                            <div>







                                <fieldset class="module aligned ">



                                    <div class="form-row field-name">


                                        <div>


                                            <label class="required" for="id_name">Name of course:</label>

                                            <input type="text" name="name" class="vTextField" maxlength="50" required=""
                                                id="id_name">



                                        </div>

                                    </div>

                                    <div class="form-row field-content">


                                        <div>


                                            <label class="required" for="id_content">Content:</label>

                                            <textarea name="content" cols="40" rows="10" class="vLargeTextField"
                                                maxlength="100" required="" id="id_content"></textarea>



                                        </div>

                                    </div>



                                    <div class="form-row field-image">


                                        <div>


                                            <label class=" required" for="id_image">Image:</label>

                                            <input type="file" name="image" accept="image/*" id="id_image">



                                        </div>

                                    </div>

                                    <div class="form-row field-intro">


                                        <div>


                                            <label class ="required" for="id_intro">Intro video:</label>

                                             <input type="text" name="intro" class="vTextField" maxlength="100" required=""
                                                id="id_intro">



                                        </div>

                                    </div>

                                    <div class="form-row field-category">


                                        <div>
                                                  
                                                  

                                            <label class="required" for="id_category">Category:</label>

                                            <div class="related-widget-wrapper" data-model-ref="Category">
                                                <select name="category" required="" id="id_category">
                                                   
                                                    {% for cat in category  %}
                                                      <option >{{cat}}</option>
                                                         {% endfor %}
                                                          <option value="" selected="">---------</option>
                                                      </select>
                                            

                                            </div>



                                        </div>

                                    </div>

                                    <div class="form-row field-instructor">


                                        <div>

                                            <label class="required" for="id_instructor">Instructor:</label>

                                            <div class="related-widget-wrapper" data-model-ref="Instructor">
                                                <select name="instructor" required="" id="id_instructor">
                                                    
                                                  
                                                      <option value="" selected="">{{ins.fname}}</option>
                                                      <option value="" selected="">---------</option>
                                                       
                                                      </select>
                                               
                                           

                                            </div>

                                          

                                        </div>

                                    </div>

                                    
                                   






                                </fieldset>


                                    <input type="submit" value="Create" name="_save">


                                   


                                







                            </div>
                        </form>
                    </div>


                    <br class="clear">
                </div>
                <!-- END Content -->
                <div id="footer"></div>
            </div>
        </div>
    </div>
    <!-- END Container -->

 
  {% endblock %}

templates/courseDetail.html
{% load static %}
{% load embed_video_tags %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous"> 
   <!-- <link rel="stylesheet" href="{% static 'css/custom.css' %}" > -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/custom-style.css' %}" > 

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />


   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

  


    
    
    <title>Welcome !</title>
  </head>



  <body>
    
 <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand mb-3" href="{% url 'index' %}">
          <img src="{% static  '/images/data-center.png' %}" width = '50px' class ="mr-3" >
          Freelearn
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" 
        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
         aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse " id="navbarSupportedContent">


          <ul class="navbar-nav mr-auto container-fluid">
           
            <li class="nav-item dropdown">

              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-list-ul"></i> Categories
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Programming</a>
                <a class="dropdown-item" href="#">web Development</a>
                <a class="dropdown-item" href="#">Mobile Development</a>
                <a class="dropdown-item" href="#"> Data Science</a>
            </li>
<li class="nav-item col-8">
                   <form class="form-inline my-2 my-lg-0 inbutton" action="{% url 'search' %}" method="post">
                        {% csrf_token %}
                            <input class="form-control form-control-lg mr-sm-0 col-8 bg-light border-0 "
                            style="border-radius: 5px 0px 0px 5px" 
                            type="search" placeholder="Search for Courses" aria-label="Search" name="query" >
                             
                            <button class="btn btn-light btn-lg  my-2 my-sm-0 ml-0 col-2" 
                          style="border-radius: 0px 5px 5px 0px;"
                            type="submit"><i class="fas fa-search text-danger "></i></button>
                        </form>
                    </li>

          </ul> 
           <p style="color:#ffffff;" class ="mr-5 mt-3  ">{{usr.fname}}&nbsp;{{usr.lname}}</p>
                <a class="btn btn-dark mr-3" href="{% url 'signout' %}">LogOut</a>
                

                

                
          
        </div>
      </nav>
 
   
 
{% block content %}

<div class="container my-5">
 <div class="row">
  <div class="col-sm-6 text-center ">
    <img src="{{courses.image.url}}" class="img-fluid rounded-start" alt="..." height="500" width="500">
  </div>
  <div class="col-sm-5 offset-sm-1">
   <h2>{{courses.name}}</h2>
   <hr>
   <p>Course Description: {{courses.content}}</p> <br>
    {{courses.instructor.fname}}&nbsp;{{courses.instructor.lname}} (Instructor)<br>
    <br>
   <small class="text-muted">
     {% if one %}
      <i class="fas fa-star fa-2x text-warning"></i>{{one}}(349)
      {% elif two %}
       <i class="fas fa-star fa-2x text-warning"></i>
        <i class="fas fa-star fa-2x text-warning"></i>   {{two}}(738)
        {% elif three %}
         <i class="fas fa-star fa-2x text-warning"></i>
          <i class="fas fa-star fa-2x text-warning"></i>
           <i class="fas fa-star fa-2x text-warning"></i>    {{three}}(2,345)
           {% elif four %}
            <i class="fas fa-star fa-2x text-warning"></i>
             <i class="fas fa-star fa-2x text-warning"></i>
              <i class="fas fa-star fa-2x text-warning"></i>
               <i class="fas fa-star fa-2x text-warning"></i>    {{four}}(12,873)
               {% elif five %}
                <i class="fas fa-star fa-2x text-warning"></i>
                 <i class="fas fa-star fa-2x text-warning"></i>
                  <i class="fas fa-star fa-2x text-warning"></i>
                   <i class="fas fa-star fa-2x text-warning"></i> 
                    <i class="fas fa-star fa-2x text-warning"></i>    {{five}}(23,455)
                    {% else %}
                    <p>No ratings yet</p>
                    {% endif %}
   </small>
  <br>
  <br>
      <a class="btn btn-danger" href="{% url 'delete' courses.pk usr.pk %}">Remove</a>
    </div>
 </div>
</div>
   <div class="container my-3">
   <h1 >Materials:</h1><br>
   <div class ="row">
   <div class="card col-sm-5 text-center">
  <h5 class="card-header"> <strong>Pdfs:</strong></h5>
  <div class="card-body">
     {% for  pd in pdf %}
   <a href="{{pd.file.url}}">{{pd.file.url}}</a><br>
   {% endfor %}
  </div>
</div>
   
    <div class="card col-sm-5 offset-sm-1 text-center">
  <h5 class="card-header">  <strong>Quiz:</strong></h5>
  <div class="card-body">
    {% for qui in quiz %}
   <a href="{{qui.quiz_url}}">{{qui.quiz_url}}</a><br>
    {% endfor %}
</div>
 </div>
</div>
</div>
   <div class="mt-4 text-center align-self-center ">
   <h3 >What you'll learn</h3>
   <ul>
    <li><span>&#10003;</span> Extensive, informative and interesting video lecture</li>
    <li><span>&#10003;</span> Complete Code demonstrated in lecture</li>
    <li><span>&#10003;</span> Instructor contact Email for questions and clarifications</li>
    <li><span>&#10003;</span> Coverage of all important primary Javascript concepts</li>
    <li><span>&#10003;</span> All Powerpoint Demonstrations Used in Course</li>
   </ul>
 </div>
 <br>
 <br>
 <div class=" text-center align-self-center"> <h2>Video Tutorials </h2></div>
   
 <div class="my-5">
 <div class="owl-carousel owl-theme mt-3">

   {% for v in videos %}
  
    <div class="item mx-5">
      <div class="card mx-4 ">
      {% video v.vid 'tiny' %}
        </div>
    </div>
    
    
   {% endfor %}
    

    
   </div>
</div>

{% endblock %}


  
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js" integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script type="text/javascript">
  $('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    autoplay:true,
    autoplayTimeout:1500,
    stagePadding:100,
    dots:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:3
        }
    }
})
  </script>
  
</body>



</html>

templates/courseview.html
{% load static %}
{% load embed_video_tags %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous"> 
   <!-- <link rel="stylesheet" href="{% static 'css/custom.css' %}" > -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/custom-style.css' %}" > 
  


    
    
    <title>Welcome !</title>
  </head>



  <body>
    
 <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand mb-3" href="{% url 'index' %}">
          <img src="{% static  '/images/data-center.png' %}" width = '50px' class ="mr-3" >
          Freelearn
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" 
        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
         aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse " id="navbarSupportedContent">


          <ul class="navbar-nav mr-auto container-fluid">
           
            <li class="nav-item dropdown">

              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-list-ul"></i> Categories
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Programming</a>
                <a class="dropdown-item" href="#">web Development</a>
                <a class="dropdown-item" href="#">Mobile Development</a>
                <a class="dropdown-item" href="#"> Data Science</a>
            </li>

            <li class="nav-item col-8">
                   <form class="form-inline my-2 my-lg-0 inbutton">
                            <input class="form-control form-control-lg mr-sm-0 col-8 bg-light border-0 "
                            style="border-radius: 5px 0px 0px 5px" 
                            type="search" placeholder="Search for Courses" aria-label="Search">
                             
                            <button class="btn btn-light btn-lg  my-2 my-sm-0 ml-0 col-2" 
                          style="border-radius: 0px 5px 5px 0px;"
                            type="submit"><i class="fas fa-search text-danger "></i></button>
                        </form>
                    </li>

          </ul>
                 <p style="color:#ffffff;" class ="mr-5 mt-3  ">{{usr.fname}}&nbsp;{{usr.lname}}</p>
                <a class="btn btn-dark mr-3" href="{% url 'signout' %}">LogOut</a>
                

                

                
          
        </div>
      </nav>
 
   
 
{% block content %}

<div class="container my-5">
 <div class="row">
  <div class="col-sm-6 text-center align-self-center">
   {% video courses.intro_Video 'small' %}
  </div>
  <div class="col-sm-5 offset-sm-1">
   <h2>{{courses.name}}</h2>
   <hr>
   <p>Course Description: {{courses.content}}</p> <br>
   <h4></h4> <br>
   <a href="{% url 'main-view' courses.pk usr.pk %}" class="btn btn-primary shadow px-5 py-2">Enroll</a>
   <h3 class="mt-5">What you'll learn</h3>
   <ul>
    <li>Extensive, informative and interesting video lecture</li>
    <li>Complete Code demonstrated in lecture</li>
    <li>Instructor contact Email for questions and clarifications</li>
    <li>Coverage of all important primary Javascript concepts</li>
    <li>All Powerpoint Demonstrations Used in Course</li>
   </ul>
  </div>
 </div>
</div>

{% endblock %}


  
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    
  
</body>



</html>

templates/inst_signup.html
{% load static%}
<!DOCTYPE html>
<html>
<head>
  
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <title>Signup Page</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
   <section>
    
        <div class="box">

            <div class="form">
                <img src="{% static '/images/profile.jpg' %}" class="user" alt="">
                <h2> Signup as Instructor</h2>
                <form class="" action="{% url 'inst_signup'%}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    <div class="inputBx">
                        <input type="text" name="firstname" placeholder="firstname" id="firstname" oninput="validation()" required autofocus>
                        <img src="images/user.png" alt="">
                    </div>
                    <div class="inputBx">
                        <input type="text" name="lastname" placeholder="lastname" id="lastname" oninput="validation()" required autofocus>
                        <img src="images/user.png" alt="">
                    </div>
                  

                    <div class="inputBx">
                        <input type="text" name="Email" placeholder="Email" id="Email" oninput="validation()" required autofocus>
                        <img src="images/user.png" alt="">
                    </div>
                    <div class="inputBx">
                        <input type="password" name="password" id="password" placeholder="Password" oninput="validation()" required>
                        <img src="images/lock.png" alt="">
                    </div>
                <label for='sex' ><b>Sex : </b></label>
            <input type='radio' name='sex' id ='sex'value='male' required>
            <label ><b>Male</b></label>
            <input type='radio' name='sex' id ='sex' value='female' required>
            <label ><b>Female</b></label><br>
            
               
                    <div class="inputBx" > 
                        <input  type="submit" name="submit" value="Signup" id="submit" disabled>
                    </div>
                </form>
                <div><span style="float: left;"><a href="#">Forgot Password </a></span>
                <span style="float:right;"><a href="{% url 'inst_login' %}">Already user?Login</a></span></div>

            </div>

        </div>
    </section>
    <script type="text/javascript">
      function validation() {
       let fname = document.getElementById("firstname").value;
        let lname = document.getElementById("lastname").value;
        let email = document.getElementById("Email").value;
        let pass = document.getElementById("password").value;
        let sex = document.getElementById("sex").value;
        if (fname != "" && pass != ""&& lname != "" && sex != "" && email != "") {
            document.getElementById("submit").disabled = false;
        }
        else {
            document.getElementById("submit").disabled = true;
        }
    }
    </script> 
   </body>
</html>

templates/quiz.html
{% extends 'inst_page.html' %}
{% block content %}
{% load static %}

  
    <link rel="stylesheet" href="{% static '/css/base.css' %}">

   <!-- <link rel="stylesheet" href="{% static '/css/dark_mode.css' %}">-->


    <link rel="stylesheet" href="{% static '/css/nav_sidebar.css' %}">
    <script src="{% static 'css/nav_sidebar.css' %}" defer=""></script>

    <link rel="stylesheet" href="{% static '/css/forms.css' %}">

    <link rel="stylesheet" href="{% static '/css/responsive.css' %}">

        

  

   


    <!-- Container -->
    <div id="container">

        <div class="main" id="main">

            <div class="content">

                <!-- Content -->
                <div id="content" class="colM">


                    <div id="content-main">

                        <form enctype="multipart/form-data"action="{% url 'quiz' %}" method="post" id="courses_form" novalidate="">
                                {% csrf_token %}
                            <div>







                                <fieldset class="module aligned ">



                                    <div class="form-row field-name">


                                        <div>


                                            <label class="required" for="id_name">Name of Quiz:</label>

                                            <input type="text" name="name" class="vTextField" maxlength="50" required=""
                                                id="id_name">



                                        </div>

                                    </div>




                                    <div class="form-row field-pdf">


                                        <div>


                                            <label class ="required" for="id_pdf">Quiz URL:</label>

                                             <input type="text" name="quiz" class="vTextField" maxlength="50" required=""
                                                id="id_quiz">



                                        </div>

                                    </div>









                                   

                                    <div class="form-row field-category">


                                        <div>
                                                  
                                                  

                                            <label class="required" for="id_category">Course:</label>

                                            <div class="related-widget-wrapper" data-model-ref="Courses">
                                                <select name="courses" required="" id="id_courses">
                                                   
                                                    {% for cat in Courses  %}
                                                      <option >{{cat}}</option>
                                                         {% endfor %}
                                                          <option value="" selected="">---------</option>
                                                      </select>
                                            

                                            </div>



                                        </div>

                                    </div>

                                  



                                </fieldset>


                                    <input type="submit" value="Add" name="_save">


                                   


                                







                            </div>
                        </form>
                    </div>


                    <br class="clear">
                </div>
                <!-- END Content -->
                <div id="footer"></div>
            </div>
        </div>
    </div>
    <!-- END Container -->

 
  {% endblock %}